version: 2

project_name: mc-router-gui
release:
  github:
    owner: Phoenix-Net
    name: mc-router-gui
before:
  hooks:
    - go mod download
builds:
  - id: mc-router-gui
    main: ./cmd/mc-router
    binary: mc-router
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "6"
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
    env:
      - CGO_ENABLED=0
archives:
  - format_overrides:
      - goos: windows
        formats: ['zip']
    files:
      - LICENSE*
      - README*
dockers:
  - image_templates:
      - "phoenixsheppy/mc-router-gui:{{ .Version }}-amd64"
      - "phoenixsheppy/mc-router-gui:latest-amd64"
    dockerfile: Dockerfile.build
    goarch: amd64
    use: buildx
    build_flag_templates:
      - --platform
      - linux/amd64
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
  - image_templates:
      - "phoenixsheppy/mc-router-gui:{{ .Version }}-arm64"
      - "phoenixsheppy/mc-router-gui:latest-arm64"
    dockerfile: Dockerfile.build
    goarch: arm64
    use: buildx
    build_flag_templates:
      - --platform
      - linux/arm64
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
  - image_templates:
      - "phoenixsheppy/mc-router-gui:{{ .Version }}-arm32v6"
      - "phoenixsheppy/mc-router-gui:latest-arm32v6"
    dockerfile: Dockerfile.build
    goarch: arm
    goarm: "6"
    use: buildx
    build_flag_templates:
      - --platform
      - linux/arm/v6
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
  - image_templates:
      - "ghcr.io/phoenix-net/{{ .ProjectName }}:{{ .Version }}-amd64"
      - "ghcr.io/phoenix-net/{{ .ProjectName }}:latest-amd64"
    dockerfile: Dockerfile.build
    goarch: amd64
    use: buildx
    build_flag_templates:
      - --platform
      - linux/amd64
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
  - image_templates:
      - "ghcr.io/phoenix-net/{{ .ProjectName }}:{{ .Version }}-arm64"
      - "ghcr.io/phoenix-net/{{ .ProjectName }}:latest-arm64"
    dockerfile: Dockerfile.build
    goarch: arm64
    use: buildx
    build_flag_templates:
      - --platform
      - linux/arm64
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
  - image_templates:
      - "ghcr.io/phoenix-net/{{ .ProjectName }}:{{ .Version }}-arm32v6"
      - "ghcr.io/phoenix-net/{{ .ProjectName }}:latest-arm32v6"
    dockerfile: Dockerfile.build
    goarch: arm
    goarm: "6"
    use: buildx
    build_flag_templates:
      - --platform
      - linux/arm/v6
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
  # Integrated image with web GUI
  - image_templates:
      - "phoenixsheppy/mc-router-gui:{{ .Version }}-gui-amd64"
      - "phoenixsheppy/mc-router-gui:gui-latest-amd64"
    dockerfile: Dockerfile.integrated
    goarch: amd64
    use: buildx
    build_flag_templates:
      - --platform
      - linux/amd64
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
    extra_files:
      - web-gui/
  - image_templates:
      - "phoenixsheppy/mc-router-gui:{{ .Version }}-gui-arm64"
      - "phoenixsheppy/mc-router-gui:gui-latest-arm64"
    dockerfile: Dockerfile.integrated
    goarch: arm64
    use: buildx
    build_flag_templates:
      - --platform
      - linux/arm64
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
    extra_files:
      - web-gui/

docker_manifests:
  - name_template: "phoenixsheppy/mc-router-gui:{{ .Version }}"
    image_templates:
      - "phoenixsheppy/mc-router-gui:{{ .Version }}-amd64"
      - "phoenixsheppy/mc-router-gui:{{ .Version }}-arm64"
      - "phoenixsheppy/mc-router-gui:{{ .Version }}-arm32v6"
  - name_template: "phoenixsheppy/mc-router-gui:latest"
    image_templates:
      - "phoenixsheppy/mc-router-gui:latest-amd64"
      - "phoenixsheppy/mc-router-gui:latest-arm64"
      - "phoenixsheppy/mc-router-gui:latest-arm32v6"
  - name_template: "ghcr.io/phoenix-net/{{ .ProjectName }}:{{ .Version }}"
    image_templates:
      - "ghcr.io/phoenix-net/{{ .ProjectName }}:{{ .Version }}-amd64"
      - "ghcr.io/phoenix-net/{{ .ProjectName }}:{{ .Version }}-arm64"
      - "ghcr.io/phoenix-net/{{ .ProjectName }}:{{ .Version }}-arm32v6"
  - name_template: "ghcr.io/phoenix-net/{{ .ProjectName }}:latest"
    image_templates:
      - "ghcr.io/phoenix-net/{{ .ProjectName }}:latest-amd64"
      - "ghcr.io/phoenix-net/{{ .ProjectName }}:latest-arm64"
      - "ghcr.io/phoenix-net/{{ .ProjectName }}:latest-arm32v6"
  # Integrated GUI manifests
  - name_template: "phoenixsheppy/mc-router-gui:{{ .Version }}-gui"
    image_templates:
      - "phoenixsheppy/mc-router-gui:{{ .Version }}-gui-amd64"
      - "phoenixsheppy/mc-router-gui:{{ .Version }}-gui-arm64"
  - name_template: "phoenixsheppy/mc-router-gui:gui-latest"
    image_templates:
      - "phoenixsheppy/mc-router-gui:gui-latest-amd64"
      - "phoenixsheppy/mc-router-gui:gui-latest-arm64"
changelog:
  filters:
    exclude:
      - '^ci:'
      - '^docs:'
      - '^misc:'
      - '^test:'
